Tech/ios14
AdevintaSpain/Sencha pull request #26
Opened 2020-09-04 09:20 UTC by gilserrap

Since EarlGrey v1 is no longer supported, the issues found when running on iOS 14 have not been addressed.

On [this PR](https://github.com/google/EarlGrey/pull/1431) you can see how the updates made in EarlGrey v2, also apply to EarlGrey v1.

The goal of this PR is to add the backported version of EarlGrey v1 to Sencha, so that we get some extra time to migrate our UI tests.

To do that, we've added a pre-built version of EarlGrey v1 with the changes to support iOS14 as a vendored framework inside Sencha.

2020-09-07 10:57 UTC, xavierjurado requested changes

2020-09-07 10:57 UTC, xavierjurado commented on Sencha.podspec
> +  s.vendored_frameworks = "EarlGrey.framework"
We should include EarlGrey license in the repository as well.

2020-09-09 09:19 UTC, gilserrap commented on Sencha/Actions/SenchaTapActions.swift
> +        }
Well, there is the issue with localisations and then, at least at Infojobs we are removing the text from the back button and setting our own accessibility label, so it may vary a lot.

2020-09-09 09:22 UTC, gilserrap commented on Sencha.podspec
> +  s.public_header_files = "EarlGrey.framework/Headers/*.h"
I assumed that this property needs to be informed when working with vendored frameworks, I haven't tried to make it work without it.

2020-09-09 09:23 UTC, gilserrap commented on Sencha.podspec
> +  s.source_files  = 'EarlGrey.framework', 'Sencha/**/*.{swift,h,m}'
Same as before, assumed it is needed when using vendored frameworks haven't tried to remove it.

2020-09-09 13:27 UTC, gilserrap commented on Sencha.podspec
> +  s.vendored_frameworks = "EarlGrey.framework"
Since EarlGrey uses an Apache License 2.0 which is the same we use for Sencha, I think we are covered.

2020-09-09 14:19 UTC, xavierjurado approved these changes

2020-10-05 11:04 UTC, merged